/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7a4193b4-c399-402d-9e37-162ce102bdb9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sG2R1O5Na",
    "aws_user_pools_web_client_id": "4fvhbnoqp3svptdjr12qoucmra",
    "oauth": {},
    "aws_user_files_s3_bucket": "profilebucket140003-showreview",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
